name: Terraform AWS CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1

jobs:

  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role_to_assume }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraformec2oidc/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraformec2oidc/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraformec2oidc/terraform
        run: terraform plan
      
      - name: Terraform Apply
        working-directory: terraformec2oidc/terraform
        run: terraform apply -auto-approve

      - name: Wait 5 Minutes 
        run: sleep 300
        
      - name: Terraform destroy
        working-directory: terraformec2oidc/terraform
        run: terraform destroy -auto-approve